spring.application.name=activityservice
spring.data.mongodb.uri = mongodb://localhost:27017/Fitness- Activity
spring.data.mongodb.database=Fitness- Activity
server.port=8082
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false


