spring.application.name=Activity-Service
spring.data.mongodb.uri = mongodb://localhost:27017/Fitness- Activity
spring.data.mongodb.database=Fitness- Activity
server.port=8082
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.client.serviceUrl.defaultZone =http://localhost:8761/eureka/
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name =activity.queue
rabbitmq.routing.key =activity.tracking

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

