spring.application.name=ai-service
server.port=8083

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=Fitness-Recommendaion

# RabbitMQ
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Gemini AI
gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}